### ISSUE TITLE
Python >=3.10 syntax in cap-anndata 0.2.0: bug when using python3.9

### ISSUE THREAD

**Issue by mfutey** [cellannotation/cap-anndata#15]
If using python3.9 and cap-anndata 0.2.0:

 File “/home/mfutey/AProject/myenv/lib/python3.9/site-packages/cap_anndata/backed_df.py”, line 68, in CapAnnDataDF
  def copy(self, deep: bool_t | None = True) -> Self:
TypeError: unsupported operand type(s) for |: ‘type’ and ‘NoneType’

**Comment by evanbiederstedt** [comment]
https://stackoverflow.com/questions/76712720/typeerror-unsupported-operand-types-for-type-and-nonetype

Version 3.10 or later only

**Comment by rm1113** [comment]
Fixed in 0.2.1 release
